# SPDX-License-Identifier: GPL-2.0
# G12A device trees (from common_drivers)
dtb-y += g12a_s905x2_2g.dtb
dtb-y += g12a_s905x2_2g_e900v22c.dtb
dtb-y += g12a_s905x2_2g_1gbit.dtb
dtb-y += g12a_s905x2_4g.dtb
dtb-y += g12a_s905x2_4g_1gbit.dtb
dtb-y += g12a_s905x2_beelink_gt_mini_a_2g.dtb
dtb-y += g12a_s905x2_beelink_gt_mini_a_4g.dtb
dtb-y += g12a_s905x2_beelink_gt1_mini_2g.dtb
dtb-y += g12a_s905x2_beelink_gt1_mini_4g.dtb
dtb-y += g12a_s905x2_mecool_m8s_plus_t2.dtb
dtb-y += g12a_s905y2_2g.dtb
dtb-y += g12a_s905y2_4g.dtb
dtb-y += g12a_s905y2_radxa_zero.dtb

# SC2 (S905X4 / S905C2) device trees for DTB bring-up testing
dtb-y += sc2_s905c2l_ah221_drm.dtb
dtb-y += sc2_s905x4_2g.dtb
dtb-y += sc2_s905x4_2g_gamebox_10x.dtb
dtb-y += sc2_s905x4_2g_1gbit.dtb
dtb-y += sc2_s905x4_4g.dtb
dtb-y += sc2_s905x4_4g_1gbit.dtb
dtb-y += sc2_s905x4_ah212_drm.dtb
dtb-y += sc2_s905x4_ah212_drm_soundbar.dtb
dtb-y += sc2_s905x4_ah212_linux.dtb
dtb-y += sc2_s905x4_ah212_mxl258c_drm.dtb
dtb-y += sc2_s905x4_buzztv_u5_4g_1gbit.dtb
dtb-y += sc2_s905x4_buzztv_x5_2g.dtb
dtb-y += sc2_s905x4_buzztv_x5_2g_1gbit.dtb
dtb-y += sc2_s905x4_buzztv_x5_4g.dtb
dtb-y += sc2_s905x4_buzztv_x5_4g_1gbit.dtb
dtb-y += sc2_s905x4_mecool_kt1.dtb
dtb-y += sc2_s905x4_sei_smb_280_id5.dtb
dtb-y += sc2_s905x4_sei_smb_280_id6.dtb
dtb-y += sc2_s905x4_sei_smb_280_id7.dtb
dtb-y += sc2_s905x4_ugoos_am7.dtb
dtb-y += sc2_s905x4_ugoos_x4.dtb
dtb-y += sc2_s905x4_x96_x4_2g.dtb
dtb-y += sc2_s905x4_x96_x4_2g_1gbit.dtb
dtb-y += sc2_s905x4_x96_x4_4g.dtb
dtb-y += sc2_s905x4_x96_x4_4g_1gbit.dtb
# sc2_s905x4_ah212_debian.dtb       # missing meson-ir-map-linux.dtsi
# sc2_s905x4_ah212_drm_1.5g.dtb     # invalid smmu phandle in pcie node

# GXL/GXBB device trees (from CoreELEC linux-amlogic mainline arch, CONFIG_ARCH_MESON=y)
# S905L/S905X/S905D/S805X/S905W boxes - dtb.img switch: copy device_trees/meson-gxl-s905x-p212.dtb to dtb.img
dtb-y += meson-gxbb-p201.dtb
dtb-y += meson-gxl-s905x-p212.dtb
dtb-y += meson-gxl-s905x-khadas-vim.dtb
dtb-y += meson-gxl-s905x-nexbox-a95x.dtb
dtb-y += meson-gxl-s905x-libretech-cc.dtb
dtb-y += meson-gxl-s905d-p230.dtb
dtb-y += meson-gxl-s905d-p231.dtb
dtb-y += meson-gxl-s905d-phicomm-n1.dtb
dtb-y += meson-gxl-s805x-p241.dtb
dtb-y += meson-gxl-s905w-p281.dtb
dtb-y += meson-gxl-s905w-tx3-mini.dtb
